<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE baloncesto[
<!ELEMENT baloncesto (equipos_de_baloncesto)>
<!ELEMENT equipos_de_baloncesto (equipo)>
<!ELEMENT equipo (nombre,ciudad,entrenador,jugadores)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT entrenador (#PCDATA)>
<!ELEMENT jugadores (#PCDATA)>
    <!ATTLIST jugadores posicion (BASE | ESCOLTA | ALERO | PIVOT) #REQUIRED>
    <!ATTLIST jugadores nacionalidad CDATA #REQUIRED>
]>

<baloncesto>
    <equipos_de_baloncesto>
        <equipo>
            <nombre></nombre>
            <ciudad></ciudad>
            <entrenador></entrenador>
            <jugadores posicion="BASE" nacionalidad="Frances"></jugadores>
        </equipo>
    </equipos_de_baloncesto>
</baloncesto>




