=== Katana86/.-Linguaxe-de-marcas-./Linguaxe de marcas/Temas/XML/DTD/autopista.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT autopista (paneles)>
<!ELEMENT paneles (elemento)>
<!ELEMENT elemento (via,pk,retencion,sentido,carrilescortados)>
    <!ATTLIST elemento tipo CDATA #REQUIRED>
    <!ATTLIST elemento fecha CDATA #IMPLIED>
<!ELEMENT via (nombre,ref,origen,destino,carriles)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT ref (#PCDATA)>
<!ELEMENT origen (#PCDATA)>
<!ELEMENT destino (#PCDATA)>
<!ELEMENT carriles EMPTY>
    <!ATTLIST carriles sentido (unico|doble) #IMPLIED>
<!ELEMENT pk EMPTY>
<!ELEMENT retencion EMPTY>
    <!ATTLIST retencion long CDATA #IMPLIED>
<!ELEMENT sentido (#PCDATA)>
<!ELEMENT carrilescortados EMPTY>
    <!ATTLIST carrilescortado valor (1|2|3|4) #IMPLIED>

=== Katana86/.-Linguaxe-de-marcas-./Linguaxe de marcas/Temas/XML/DTD/405_Autopista.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE autopista SYSTEM "autopista.dtd">


<autopista>
    <paneles>
        <elemento tipo="" fecha="">
            <via>
                <nombre></nombre>
                <ref></ref>
                <origen></origen>
                <destino></destino>
                <carriles sentido="unico"/>
            </via>
            <pk/>
            <retencion long=""></retencion>
            <sentido></sentido>
            <carrilescortados valor="3"/>
        </elemento>
    </paneles> 
</autopista>
