<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!--Declaraciones-->
<!DOCTYPE mensaje [
<!ELEMENT mensaje (de,para,asunto,adjunto)>
<!ELEMENT de EMPTY>
<!ELEMENT para EMPTY>
<!ELEMENT asunto EMPTY>
<!ELEMENT adjunto EMPTY>
]>

<!--CuerpoXML-->

<root>
    <mensaje>
	<de>maria@gmail.com</de>
	<para>ignacio@gmail.com</para>
	<para>pedro@edu.xunta.es</para>
	<asunto>Env√≠oche os arquivos</asunto>
	<adjunto>D:\fotos\dePesca.jpg</adjunto>
	<adjunto>D:\docs\carta.odt</adjunto>
	<adjunto>D:\fotos\naCea.jpg</adjunto>
</mensaje>
</root>

